// @ts-check
const eslint = require('@eslint/js');
const { defineConfig } = require('eslint/config');
const tseslint = require('typescript-eslint');
const angular = require('angular-eslint');
const boundaries = require('eslint-plugin-boundaries');
const eslintConfigPrettier = require('eslint-config-prettier');

module.exports = defineConfig([
  {
    // Generated by `supabase gen types typescript`; regenerated as the DB schema
    // evolves, so it shouldn't be hand-edited to satisfy our style rules.
    ignores: ['src/app/core/models/database.types.ts'],
  },
  {
    files: ['**/*.ts'],
    extends: [
      eslint.configs.recommended,
      tseslint.configs.recommended,
      tseslint.configs.stylistic,
      angular.configs.tsRecommended,
    ],
    processor: angular.processInlineTemplates,
    rules: {
      '@angular-eslint/directive-selector': [
        'error',
        {
          type: 'attribute',
          prefix: 'app',
          style: 'camelCase',
        },
      ],
      '@angular-eslint/component-selector': [
        'error',
        {
          type: 'element',
          prefix: 'app',
          style: 'kebab-case',
        },
      ],
      // Unused callback params (route, state, next...) and empty stub bodies are
      // expected on framework hooks (guards, interceptors, ErrorHandler) before
      // their implementation lands.
      '@typescript-eslint/no-unused-vars': ['error', { args: 'none' }],
      '@typescript-eslint/no-empty-function': ['error', { allow: ['methods', 'arrowFunctions'] }],
    },
  },
  // Architectural boundaries between core, shared and features (src/app/*.ts files
  // like app.config.ts stay unmatched/unknown and are left unchecked by design).
  {
    files: ['src/app/**/*.ts'],
    plugins: { boundaries },
    settings: {
      // The TypeScript resolver, not the plain node one, so `boundaries` can
      // follow the `@core/*` style aliases from tsconfig.json. With the node
      // resolver an aliased import resolves to nothing, and a rule that cannot
      // resolve an import cannot classify it — the architecture checks would
      // pass by simply never seeing the violations.
      'import/resolver': {
        typescript: {
          project: './tsconfig.json',
        },
      },
      'boundaries/elements': [
        { type: 'core', pattern: 'src/app/core/**' },
        { type: 'shared', pattern: 'src/app/shared/**' },
        { type: 'features', pattern: 'src/app/features/(*)/**', capture: ['featureName'] },
      ],
    },
    rules: {
      'boundaries/dependencies': [
        'error',
        {
          default: 'disallow',
          policies: [
            {
              from: { element: { type: 'core' } },
              allow: { to: { element: { type: 'core' } } },
              message: 'core must be self-contained: it cannot import from shared or features.',
            },
            {
              from: { element: { type: 'shared' } },
              allow: { to: { element: { type: 'shared' } } },
              message: 'shared must be self-contained: it cannot import from core or features.',
            },
            {
              from: { element: { type: 'features' } },
              allow: {
                to: [
                  { element: { types: { anyOf: ['core', 'shared'] } } },
                  {
                    element: {
                      type: 'features',
                      captured: { featureName: '{{from.featureName}}' },
                    },
                  },
                ],
              },
              message: 'features may only import core, shared, and files within the same feature.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['**/*.html'],
    extends: [angular.configs.templateRecommended, angular.configs.templateAccessibility],
    rules: {},
  },
  eslintConfigPrettier,
]);
